name: Build
on: push

jobs:
  build:
    name: Continuous Deployment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python3 setup.py develop

      - name: Lint
        run: pylint app/ integration_tests/

      - name: Unit Tests
        run: pytest --cov=app tests/

      - name: Integration Tests
        run: cd integration_tests && docker-compose up integration_tests
